const QUESTIONS = {

easy: [

{question:"Who directed Jurassic Park?",choices:["Steven Spielberg","James Cameron","George Lucas","Ridley Scott"],correct:0},
{question:"Which movie features the quote 'I'll be back'?",choices:["Predator","The Terminator","RoboCop","Commando"],correct:1},
{question:"Who played Jack in Titanic?",choices:["Brad Pitt","Johnny Depp","Leonardo DiCaprio","Tom Cruise"],correct:2},
{question:"What is the name of the toy cowboy in Toy Story?",choices:["Buzz","Woody","Jessie","Bullseye"],correct:1},
{question:"Which movie features a shark named Bruce?",choices:["Deep Blue Sea","Jaws","Sharknado","The Meg"],correct:1},
{question:"What is the name of Harry Potter's owl?",choices:["Crookshanks","Hedwig","Scabbers","Fawkes"],correct:1},
{question:"Which movie features Forrest Gump?",choices:["Rain Man","Cast Away","Forrest Gump","Big"],correct:2},
{question:"Who voices Shrek?",choices:["Eddie Murphy","Mike Myers","Jim Carrey","Will Ferrell"],correct:1},
{question:"Which movie features 'May the Force be with you'?",choices:["Star Trek","Star Wars","Dune","Avatar"],correct:1},
{question:"What pill does Neo take in The Matrix?",choices:["Blue","Green","Red","Yellow"],correct:2},
{question:"Who plays Iron Man in the MCU?",choices:["Chris Evans","Robert Downey Jr.","Mark Ruffalo","Chris Hemsworth"],correct:1},
{question:"Which animated movie features Elsa?",choices:["Frozen","Tangled","Moana","Encanto"],correct:0},
{question:"What city does Batman protect?",choices:["Metropolis","Central City","Gotham","Star City"],correct:2},
{question:"Who directed Avatar?",choices:["James Cameron","Christopher Nolan","Peter Jackson","Ridley Scott"],correct:0},
{question:"Which movie features cloned dinosaurs?",choices:["Jurassic Park","King Kong","Godzilla","Cloverfield"],correct:0},
{question:"Who played the Joker in The Dark Knight?",choices:["Jared Leto","Heath Ledger","Jack Nicholson","Joaquin Phoenix"],correct:1},
{question:"Which movie features Rocky Balboa?",choices:["Creed","Rocky","Raging Bull","Southpaw"],correct:1},
{question:"What is Simba's father's name?",choices:["Scar","Mufasa","Zazu","Timon"],correct:1},
{question:"Which movie features a DeLorean time machine?",choices:["Back to the Future","Looper","Timecop","Primer"],correct:0},
{question:"Who directed E.T.?",choices:["George Lucas","Steven Spielberg","Tim Burton","James Cameron"],correct:1},
{question:"Which movie features the quote 'Why so serious?'",choices:["Joker","The Dark Knight","Batman Begins","Suicide Squad"],correct:1},
{question:"Who says 'To infinity and beyond'?",choices:["Woody","Buzz Lightyear","Rex","Forky"],correct:1},
{question:"Which movie features blue aliens called Na'vi?",choices:["Avatar","Dune","Star Wars","Guardians of the Galaxy"],correct:0},
{question:"Who played Jack Sparrow?",choices:["Orlando Bloom","Johnny Depp","Tom Hardy","Javier Bardem"],correct:1},
{question:"Which movie includes 'Life is like a box of chocolates'?",choices:["Forrest Gump","Big Fish","The Green Mile","Cast Away"],correct:0}

],

medium: [

{question:"Who directed The Dark Knight?",choices:["Christopher Nolan","Zack Snyder","Matt Reeves","Tim Burton"],correct:0},
{question:"Which movie won Best Picture in 1994?",choices:["Forrest Gump","Pulp Fiction","The Shawshank Redemption","Braveheart"],correct:0},
{question:"Who played Neo in The Matrix?",choices:["Brad Pitt","Keanu Reeves","Johnny Depp","Tom Cruise"],correct:1},
{question:"Which actor plays Wolverine?",choices:["Hugh Jackman","Chris Hemsworth","Ryan Reynolds","Chris Evans"],correct:0},
{question:"Which movie features the character Maximus?",choices:["Gladiator","Troy","300","Spartacus"],correct:0},
{question:"Who directed Pulp Fiction?",choices:["Quentin Tarantino","Guy Ritchie","Martin Scorsese","David Fincher"],correct:0},
{question:"Which movie features the quote 'Here's Johnny!'",choices:["Psycho","The Shining","Halloween","Carrie"],correct:1},
{question:"Which actor played Deadpool?",choices:["Ryan Reynolds","Chris Pratt","Paul Rudd","Mark Ruffalo"],correct:0},
{question:"Who directed Lord of the Rings?",choices:["Peter Jackson","James Cameron","Ridley Scott","Sam Raimi"],correct:0},
{question:"Which film introduced the character Hannibal Lecter?",choices:["Silence of the Lambs","Hannibal","Red Dragon","Manhunter"],correct:3},
{question:"Which movie features a computer called HAL 9000?",choices:["2001: A Space Odyssey","Alien","Blade Runner","Moon"],correct:0},
{question:"Who directed Inception?",choices:["Christopher Nolan","Denis Villeneuve","James Cameron","Ridley Scott"],correct:0},
{question:"Which movie features Tony Montana?",choices:["Scarface","Goodfellas","Casino","The Godfather"],correct:0},
{question:"Which actor played The Dude in The Big Lebowski?",choices:["Jeff Bridges","John Goodman","Steve Buscemi","Nick Nolte"],correct:0},
{question:"Which movie features the quote 'Say hello to my little friend'?",choices:["Scarface","Carlito's Way","Goodfellas","Heat"],correct:0},
{question:"Who directed Fight Club?",choices:["David Fincher","Quentin Tarantino","Christopher Nolan","Ridley Scott"],correct:0},
{question:"Which actor played the T-800?",choices:["Sylvester Stallone","Arnold Schwarzenegger","Bruce Willis","Jean-Claude Van Damme"],correct:1},
{question:"Which movie features a theme park of dinosaurs?",choices:["Jurassic Park","Westworld","King Kong","Godzilla"],correct:0},
{question:"Which movie features a character named Travis Bickle?",choices:["Taxi Driver","Heat","Drive","Collateral"],correct:0},
{question:"Who directed Blade Runner?",choices:["Ridley Scott","James Cameron","George Lucas","Steven Spielberg"],correct:0},
{question:"Which movie features the quote 'I see dead people'?",choices:["The Sixth Sense","The Others","The Ring","Poltergeist"],correct:0},
{question:"Which actor plays Thor?",choices:["Chris Evans","Chris Pratt","Chris Hemsworth","Chris Pine"],correct:2},
{question:"Which movie features Marty McFly?",choices:["Back to the Future","Teen Wolf","Timecop","Looper"],correct:0},
{question:"Who directed Titanic?",choices:["James Cameron","Steven Spielberg","Ron Howard","Ridley Scott"],correct:0},
{question:"Which movie features the character Ellen Ripley?",choices:["Alien","Predator","Terminator","Event Horizon"],correct:0}

],

hard: [

{question:"Who composed the score for Star Wars?",choices:["Hans Zimmer","John Williams","James Horner","Howard Shore"],correct:1},
{question:"Which film won Best Picture in 1972?",choices:["The Godfather","Cabaret","Patton","Rocky"],correct:0},
{question:"Who directed The Seventh Seal?",choices:["Ingmar Bergman","Akira Kurosawa","Federico Fellini","Andrei Tarkovsky"],correct:0},
{question:"Which movie features the character Anton Chigurh?",choices:["No Country for Old Men","There Will Be Blood","Sicario","Fargo"],correct:0},
{question:"Who directed Parasite?",choices:["Park Chan-wook","Bong Joon-ho","Kim Jee-woon","Lee Chang-dong"],correct:1},
{question:"Which actor played Daniel Plainview?",choices:["Daniel Day-Lewis","Gary Oldman","Christian Bale","Philip Seymour Hoffman"],correct:0},
{question:"Which film introduced the character Jason Bourne?",choices:["The Bourne Identity","The Bourne Supremacy","The Bourne Ultimatum","The Bourne Legacy"],correct:0},
{question:"Who directed The Grand Budapest Hotel?",choices:["Wes Anderson","Paul Thomas Anderson","Sofia Coppola","Spike Jonze"],correct:0},
{question:"Which movie features the quote 'I'm the king of the world'?",choices:["Titanic","The Aviator","Catch Me If You Can","The Wolf of Wall Street"],correct:0},
{question:"Who directed The Social Network?",choices:["David Fincher","Aaron Sorkin","Danny Boyle","Christopher Nolan"],correct:0},
{question:"Which movie features Cobb as the main character?",choices:["Inception","Tenet","Interstellar","Memento"],correct:0},
{question:"Which actor played Vito Corleone in The Godfather?",choices:["Al Pacino","Robert De Niro","Marlon Brando","James Caan"],correct:2},
{question:"Who directed The Thing (1982)?",choices:["John Carpenter","Wes Craven","Tobe Hooper","George Romero"],correct:0},
{question:"Which movie features the Nostromo spaceship?",choices:["Alien","Aliens","Prometheus","Event Horizon"],correct:0},
{question:"Who directed The Prestige?",choices:["Christopher Nolan","David Fincher","James Cameron","Ridley Scott"],correct:0},
{question:"Which actor played Maximus?",choices:["Russell Crowe","Gerard Butler","Joaquin Phoenix","Colin Farrell"],correct:0},
{question:"Which movie features the character Donnie Darko?",choices:["Donnie Darko","Dark City","Primer","Coherence"],correct:0},
{question:"Who directed Pan's Labyrinth?",choices:["Guillermo del Toro","Alejandro Iñárritu","Alfonso Cuarón","Pedro Almodóvar"],correct:0},
{question:"Which movie features the character Tyler Durden?",choices:["Fight Club","Seven","American Psycho","The Machinist"],correct:0},
{question:"Who directed Heat?",choices:["Michael Mann","Brian De Palma","Martin Scorsese","Ridley Scott"],correct:0},
{question:"Which film features the quote 'I drink your milkshake'?",choices:["There Will Be Blood","No Country for Old Men","The Master","Magnolia"],correct:0},
{question:"Who directed Mad Max: Fury Road?",choices:["George Miller","James Cameron","Ridley Scott","Denis Villeneuve"],correct:0},
{question:"Which movie features Deckard?",choices:["Blade Runner","Minority Report","Total Recall","Dark City"],correct:0},
{question:"Which actor played Joker in Joker (2019)?",choices:["Joaquin Phoenix","Jared Leto","Heath Ledger","Jack Nicholson"],correct:0},
{question:"Who directed Moonlight?",choices:["Barry Jenkins","Spike Lee","Ryan Coogler","Jordan Peele"],correct:0}

],

insane: [

{question:"Which Tarkovsky film features a mysterious room granting wishes?",choices:["Solaris","Stalker","Mirror","Andrei Rublev"],correct:1},
{question:"Which Kurosawa film inspired The Magnificent Seven?",choices:["Yojimbo","Seven Samurai","Rashomon","Ran"],correct:1},
{question:"Who directed Eraserhead?",choices:["David Lynch","John Waters","David Cronenberg","Terry Gilliam"],correct:0},
{question:"Which film features the character Alex DeLarge?",choices:["A Clockwork Orange","Brazil","THX 1138","1984"],correct:0},
{question:"Who directed Mulholland Drive?",choices:["David Lynch","Roman Polanski","David Fincher","Brian De Palma"],correct:0},
{question:"Which movie features the Overlook Hotel?",choices:["The Shining","Doctor Sleep","1408","The Others"],correct:0},
{question:"Who directed Persona?",choices:["Ingmar Bergman","Lars von Trier","Andrei Tarkovsky","Michael Haneke"],correct:0},
{question:"Which film features a replicant named Roy Batty?",choices:["Blade Runner","Ghost in the Shell","Akira","Metropolis"],correct:0},
{question:"Who directed The Lighthouse?",choices:["Robert Eggers","Ari Aster","Jordan Peele","James Wan"],correct:0},
{question:"Which movie features the character Patrick Bateman?",choices:["American Psycho","Wall Street","Fight Club","Seven"],correct:0},
{question:"Who directed Synecdoche, New York?",choices:["Charlie Kaufman","Spike Jonze","Michel Gondry","Paul Thomas Anderson"],correct:0},
{question:"Which film features the phrase 'This is your brain on drugs' parody?",choices:["Requiem for a Dream","Trainspotting","Fear and Loathing in Las Vegas","Spun"],correct:0},
{question:"Who directed Oldboy (2003)?",choices:["Bong Joon-ho","Park Chan-wook","Kim Ki-duk","Lee Chang-dong"],correct:1},
{question:"Which movie features the character Tetsuo?",choices:["Akira","Ghost in the Shell","Perfect Blue","Paprika"],correct:0},
{question:"Who directed Dogtooth?",choices:["Yorgos Lanthimos","Michael Haneke","Gaspar Noé","Lars von Trier"],correct:0},
{question:"Which film features a cult called the Paimon worshippers?",choices:["Hereditary","Midsommar","The Witch","The Ritual"],correct:0},
{question:"Who directed Enter the Void?",choices:["Gaspar Noé","Harmony Korine","Nicolas Winding Refn","Claire Denis"],correct:0},
{question:"Which movie features the character Lester Burnham?",choices:["American Beauty","The Ice Storm","Magnolia","Revolutionary Road"],correct:0},
{question:"Who directed The Holy Mountain?",choices:["Alejandro Jodorowsky","Luis Buñuel","Federico Fellini","Terry Gilliam"],correct:0},
{question:"Which movie features the character Anton Ego?",choices:["Ratatouille","Chef","Burnt","The Menu"],correct:0},
{question:"Who directed Under the Skin?",choices:["Jonathan Glazer","Denis Villeneuve","Alex Garland","Darren Aronofsky"],correct:0},
{question:"Which movie features the character Frank Booth?",choices:["Blue Velvet","Wild at Heart","Lost Highway","Mulholland Drive"],correct:0},
{question:"Who directed Climax?",choices:["Gaspar Noé","Lars von Trier","Ari Aster","Nicolas Winding Refn"],correct:0},
{question:"Which film features the character Travis Henderson?",choices:["Paris, Texas","Wings of Desire","Fitzcarraldo","Aguirre"],correct:0},
{question:"Who directed Possession (1981)?",choices:["Andrzej Żuławski","Roman Polanski","David Cronenberg","Dario Argento"],correct:0}

],
kevin: [

{question:"Which film won Best Picture at the 1976 Academy Awards?",choices:["Taxi Driver","Rocky","Network","All the President's Men"],correct:1},
{question:"Who directed the 1927 silent science-fiction film Metropolis?",choices:["Fritz Lang","F.W. Murnau","Sergei Eisenstein","Carl Dreyer"],correct:0},
{question:"Which actor played the original cinematic Dracula in 1931?",choices:["Bela Lugosi","Lon Chaney","Christopher Lee","Peter Cushing"],correct:0},
{question:"Which film was the first feature-length animated movie ever released?",choices:["Fantasia","Snow White and the Seven Dwarfs","Pinocchio","Steamboat Willie"],correct:1},
{question:"Who composed the score for The Good, the Bad and the Ugly?",choices:["Nino Rota","Ennio Morricone","John Barry","Lalo Schifrin"],correct:1},
{question:"Which film features the line 'Forget it, Jake. It's Chinatown.'?",choices:["The Godfather","Chinatown","Taxi Driver","Serpico"],correct:1},
{question:"Who directed the 1954 samurai epic Seven Samurai?",choices:["Masaki Kobayashi","Akira Kurosawa","Kenji Mizoguchi","Yasujiro Ozu"],correct:1},
{question:"Which movie features the character HAL 9000?",choices:["Solaris","2001: A Space Odyssey","Silent Running","Moon"],correct:1},
{question:"Which film won the Palme d'Or at Cannes in 1994?",choices:["Pulp Fiction","Three Colors: Red","Chungking Express","The Piano"],correct:0},
{question:"Who directed the cult film Donnie Darko?",choices:["Richard Kelly","Darren Aronofsky","David Fincher","Spike Jonze"],correct:0},
{question:"Which actor portrayed T.E. Lawrence in Lawrence of Arabia?",choices:["Peter O'Toole","Alec Guinness","Anthony Quinn","Omar Sharif"],correct:0},
{question:"Which director made the film Stalker?",choices:["Andrei Tarkovsky","Sergei Parajanov","Elem Klimov","Dziga Vertov"],correct:0},
{question:"Which movie features the character Travis Bickle?",choices:["Taxi Driver","Mean Streets","Dog Day Afternoon","Serpico"],correct:0},
{question:"Which cinematographer shot Blade Runner (1982)?",choices:["Roger Deakins","Jordan Cronenweth","Vittorio Storaro","Dean Cundey"],correct:1},
{question:"Which film features the character Alex DeLarge?",choices:["Brazil","A Clockwork Orange","THX 1138","Videodrome"],correct:1},
{question:"Which director made Mulholland Drive?",choices:["David Lynch","Roman Polanski","Brian De Palma","David Cronenberg"],correct:0},
{question:"Which film won Best Picture in 2009?",choices:["The Hurt Locker","Avatar","Up in the Air","Inglourious Basterds"],correct:0},
{question:"Which movie introduced the character Anton Chigurh?",choices:["Sicario","No Country for Old Men","Hell or High Water","Fargo"],correct:1},
{question:"Which director made the film Persona?",choices:["Ingmar Bergman","Carl Dreyer","Federico Fellini","Michelangelo Antonioni"],correct:0},
{question:"Which actor played Daniel Plainview in There Will Be Blood?",choices:["Daniel Day-Lewis","Gary Oldman","Philip Seymour Hoffman","Joaquin Phoenix"],correct:0},
{question:"Which movie features the quote 'I drink your milkshake'?",choices:["There Will Be Blood","Magnolia","The Master","No Country for Old Men"],correct:0},
{question:"Which director made The Holy Mountain?",choices:["Luis Buñuel","Alejandro Jodorowsky","Federico Fellini","Pier Paolo Pasolini"],correct:1},
{question:"Which film features the character Roy Batty?",choices:["Blade Runner","Ghost in the Shell","Akira","Metropolis"],correct:0},
{question:"Which director made the film Climax?",choices:["Gaspar Noé","Nicolas Winding Refn","Lars von Trier","Yorgos Lanthimos"],correct:0},
{question:"Which film features the character Lester Burnham?",choices:["American Beauty","The Ice Storm","Magnolia","Revolutionary Road"],correct:0}

]

};
